### ISSUE TITLE
BuildFailed

### ISSUE THREAD

**Issue by takajapan** [magickworx/SocialAccountKitSwift#1]
初歩的な質問で申し訳ありません。SocialAccountKitSwiftFatBinaryをBuildしようとすると
以下のようなエラーがでてしまうのですが、どのように対応したらよいでしょうか。
fatal error: lipo: can't open input file: /Users/〜/SocialAccountKitSwift-master/SocialAccountKit.framework/SocialAccountKit (No such file or directory)

**Comment by magickworx** [comment]
修正版をコミットしました。
もう一度 clone あるいは download してビルドして下さい。
