### ISSUE TITLE
DemoアプリでのTwitterアカウント登録

### ISSUE THREAD

**Issue by takajapan** [magickworx/SocialAccountKitSwift#2]
先程はありがとうございました。無事Buildできました。
TwitterのAPIkey等を登録してアカウント登録しようとすると以下のエラーがでます。
（実機でも同様でした）FBは試しておりません。度々すみませんがよろしくおねがいします。
<img width="375" alt="2018-02-25 23 02 44" src="https://user-images.githubusercontent.com/36810754/36642254-3b1ec94e-1a80-11e8-9f87-375a1d7468f0.png">

**Comment by magickworx** [comment]
Twitter 側の設定で指定している callback URL が原因の可能性があります。
Twitter.plist に ConsumerKey と ConsumerSecret  のみを指定して、Twitter 側の callback URL は swift-oauth:// にするとどうでしょうか。

**Comment by takajapan** [comment]
ありがとうございます。直りました。お手数おかけしてすみませんでした。
